number1 = input("Enter the first number: ")
number2 = input("Enter the second number: ")
addition = int(number1) + int(number2)
subtraction = int(number1) - int(number2)
multiplication = int(number1) * int(number2)
division = int(number1) / int(number2)
print("Addition: ", addition)
print("Subtraction: ", subtraction)
print("Multiplication: ", multiplication)
print("Division: ", division)